# Generated by Django 5.0.9 on 2024-10-05 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('markets', '0002_alter_symboltype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='markets.broker', verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='journal.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='history',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='history',
            name='operation',
            field=models.CharField(choices=[('DE', 'Deposit'), ('DI', 'Dividends'), ('PC', 'Position Close'), ('WD', 'Withdrawal')], max_length=20, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='history',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='journal.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='history',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='position',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='journal.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='position',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Close price'),
        ),
        migrations.AlterField(
            model_name='position',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed at'),
        ),
        migrations.AlterField(
            model_name='position',
            name='closed_manually',
            field=models.BooleanField(blank=True, null=True, verbose_name='Closed manually'),
        ),
        migrations.AlterField(
            model_name='position',
            name='commissions',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Commissions'),
        ),
        migrations.AlterField(
            model_name='position',
            name='modifications',
            field=models.JSONField(default=dict, verbose_name='Modifications'),
        ),
        migrations.AlterField(
            model_name='position',
            name='open_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Open price'),
        ),
        migrations.AlterField(
            model_name='position',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened at'),
        ),
        migrations.AlterField(
            model_name='position',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sl_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Stop loss price'),
        ),
        migrations.AlterField(
            model_name='position',
            name='swaps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Swaps'),
        ),
        migrations.AlterField(
            model_name='position',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='markets.symbol', verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='position',
            name='ticket',
            field=models.PositiveBigIntegerField(verbose_name='Ticket no.'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tp_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Take profit price'),
        ),
        migrations.AlterField(
            model_name='position',
            name='volume',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Volume'),
        ),
    ]
