# Generated by Django 5.0.9 on 2024-10-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('markets', models.ManyToManyField(blank=True, related_name='brokers', to='markets.market')),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
            },
        ),
        migrations.CreateModel(
            name='SymbolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Symbol Type',
                'verbose_name_plural': 'Symbol Types',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('brokers', models.ManyToManyField(blank=True, related_name='symbols', to='markets.broker')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='markets.market')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='markets.symboltype')),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbols',
                'unique_together': {('code', 'market')},
            },
        ),
    ]
