# Generated by Django 5.0.9 on 2024-10-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symboltype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='broker',
            name='markets',
            field=models.ManyToManyField(blank=True, related_name='brokers', to='markets.market', verbose_name='Markets'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='brokers',
            field=models.ManyToManyField(blank=True, related_name='symbols', to='markets.broker', verbose_name='Brokers'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='markets.market', verbose_name='Market'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='markets.symboltype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='symboltype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
